### ISSUE TITLE
issue downloading eurchf ticks from dukascopy

### ISSUE THREAD

**Issue by kalaytan** [cuemacro/findatapy#9]
I have same code working for gbpusd, eurusd but not eurchf.

1. dukascopy have eurchf and it can be downloaded
https://datafeed.dukascopy.com/datafeed/GBPUSD/2016/11/05/18h_ticks.bi5
https://datafeed.dukascopy.com/datafeed/EURCHF/2016/11/05/21h_ticks.bi5

code:
```
import sys
sys.path.insert(0, 'C:\\Python\\findatapy')
from findatapy.market import Market, MarketDataRequest, MarketDataGenerator
import datetime as dt
import calendar
from arctic import Arctic


''' download and clean '''
def download_data(start_date, finish_date, ticker):
    md_request = MarketDataRequest(start_date=start_date, finish_date=finish_date,
                                   category='fx', fields=['bid', 'ask'], freq='tick',
                                   data_source='dukascopy', tickers=[ticker])
    market = Market(market_data_generator=MarketDataGenerator())
    # download and return data
    return market.fetch_market(md_request)



data = download_data ('01 Jan 2016', '3 Jan 2016', 'EURCHF')
print(data.tail(3))
```
error output:

`Traceback (most recent call last):
  File "C:/python/MA retracer/dukascopy2Arctic.py", line 22, in <module>
    data = download_data ('01 Jan 2016', '3 Jan 2016', 'EURCHF')
  File "C:/python/MA retracer/dukascopy2Arctic.py", line 18, in download_data
    return market.fetch_market(md_request)
  File "C:\Python\findatapy\findatapy\market\market.py", line 68, in fetch_market
    environment = md_request.environment)
  File "C:\Python\findatapy\findatapy\market\market.py", line 214, in get_fx_cross
    cut = cut, source = source, cache_algo = cache_algo, type = 'spot', fields = fields)
  File "C:\Python\findatapy\findatapy\market\market.py", line 186, in get_fx_cross_tick
    cross_vals = market_data_generator.fetch_market_data(market_data_request)
  File "C:\Python\findatapy\findatapy\market\marketdatagenerator.py", line 137, in fetch_market_data
    data_frame_agg = self.download_intraday_tick(market_data_request, data_vendor)
  File "C:\Python\findatapy\findatapy\market\marketdatagenerator.py", line 248, in download_intraday_tick
    data_frame_single = data_vendor.load_ticker(market_data_request_single)
  File "C:\Python\findatapy\findatapy\market\datavendorweb.py", line 575, in load_ticker
    market_data_request_vendor = self.construct_vendor_market_data_request(market_data_request)
  File "C:\Python\findatapy\findatapy\market\datavendor.py", line 70, in construct_vendor_market_data_request
    symbols_vendor = self.translate_to_vendor_ticker(market_data_request)
  File "C:\Python\findatapy\findatapy\market\datavendor.py", line 145, in translate_to_vendor_ticker
    self.config.convert_library_to_vendor_ticker(category, source, freq, cut, ticker))
  File "C:\Python\findatapy\findatapy\util\configmanager.py", line 220, in convert_library_to_vendor_ticker
    category + '.' + source + '.'+ freq + '.' + cut + '.' + ticker]
KeyError: 'fx.dukascopy.tick.NYC.EURCHF'`

**Comment by kalaytan** [comment]
found the solution and created pull request #10
